[workspace]
resolver = "3"
members = ["collections", "control_flow", "enums", "error_handling", "functional_programming", "functions", "guessing_game", "hello-cargo", "minigrep", "ownership","packages_crates", "reference", "slice", "structs", "variables"]
